# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import math_functions as module_0


def test_case_0():
    bool_0 = True
    int_0 = module_0.multiply(bool_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = 1618
    none_type_0 = None
    module_0.add(int_0, none_type_0)
